/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "touwkydlhzxgwhnxpnui"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdXdreWRsaHp4Z3dobnhwbnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODQ4ODAsImV4cCI6MjA3NDU2MDg4MH0.GYLJ-JcTz6RVZmg8cqyzlnFUpBP6pwxtCj1xGWMBmss"
